### ISSUE TITLE
Keep the user logged after we close the application.

### ISSUE THREAD

**Issue by GustavoMottaTranche** [CESARBR/corona-mission#21]
It's not good when we have to do login every time after we close the app.

Save in the locally a token or a ID that makes possible to make login in the firebase again, so we can keep context.

We can save the uid, and infos we use in the screen locally, and do not make login again, and use all locally untill the user make logout, but we lose firebase analisys, remember we won't save passwords, only datas we really use in application.

**Additional context**

**Comment by maioni** [comment]
Fixed!
