### ISSUE TITLE
Status bar appears hidden

### ISSUE THREAD

**Issue by JoseClaudioADS** [CESARBR/corona-mission#26]
**Describe the bug**
Status bar stay hidden on my phone. Galaxy S10.

**To Reproduce**
1. Go to login Google/e-mail pages

**Expected behavior**
A status bar visible

**Screenshots**
![Screenshot_20200402-162027_Corona Mission](https://user-images.githubusercontent.com/1438340/78293395-e0c8e980-74fe-11ea-9273-a9f896a68ea1.jpg)

**Desktop (please complete the following information):**
 - OS: Android 10

**Smartphone (please complete the following information):**
 - Device: Galaxy S10

**Additional context**
This behavior appears in others screens. Like home.

**Comment by maioni** [comment]
Fixed!
