### ISSUE TITLE
[Bug] Unexpected message in the mission counter

### ISSUE THREAD

**Issue by arianalima** [CESARBR/corona-mission#30]
**Describe the bug**
"NaN dias sem missão" message is shown in contacts with whom no mission was done

**To Reproduce**
1. Authenticate
2. Add a contact
3. Click in the contact
4. Go back to the previous screen
5. See error message as shown in the screenshot

**Expected behavior**
"Realize a sua primeira missão" message shown

**Screenshots**
![image](https://user-images.githubusercontent.com/14033970/78318161-7cc41680-753a-11ea-8e63-1fb09cf0812c.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J8
 - OS: Android 9

**Comment by GustavoMottaTranche** [comment]
Same issue as #47

**Comment by maioni** [comment]
Fixed!
