### ISSUE TITLE
[Bug] Scroll issue in contacts list

### ISSUE THREAD

**Issue by arianalima** [CESARBR/corona-mission#31]
**Describe the bug**
User can't scroll the contact list. It is not possible to see more than 4 people (depending on screen size more or less contacts can be seen).

**To Reproduce**
1. Log in the application
2. Create 5 or more contacts
3. Try to scroll the screen to see the full list

**Expected behavior**
Contacts list scrolled down and user can see all his contacts

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J8
 - OS: Android 9

**Comment by maioni** [comment]
Fixed!
