### ISSUE TITLE
[UX] On screens where there is no hamburger menu or the back button on top, it's possible scroll the screen vertically

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#33]
**Describe the bug**
[UX] 7On screens where there is no hamburger menu or the back button on top, it's possible scroll the screen vertically

**To Reproduce**
1. Go to login (should login type: google or email) screen and try to scroll vertically.
2. Go to login (name / password) screen and try to scroll vertically.

**Actual behavior**
1/2. It's possible to scroll vertically

**Expected behavior**
1/2. It's NOT possible to scroll vertically

**Screenshots**
![image](https://user-images.githubusercontent.com/6604846/78321953-c06f4e00-7543-11ea-84b4-cf39bfc56414.png)
![image](https://user-images.githubusercontent.com/6604846/78321956-c36a3e80-7543-11ea-8db5-b6777fde0dcd.png)
![image](https://user-images.githubusercontent.com/6604846/78321960-c6652f00-7543-11ea-90f5-5acacec1cc8f.png)
![image](https://user-images.githubusercontent.com/6604846/78321970-ce24d380-7543-11ea-8004-789819a64ec4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by vieira-rodrigo** [comment]
Não reproduzido, possivelmente corrigido no fix #32

**Comment by maioni** [comment]
Fixed!
