### ISSUE TITLE
[BUG] password reset code validation screen is not built as planned (incomplete flow)

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#36]
**Describe the bug**
[BUG] password reset code validation screen is not built as planned (incomplete flow)

**To Reproduce**
1. Open the application (log out if log in)
2. Select to login with Email
3. Select to Recover Password
4. Input a register and valid email
5. Check the verification code screen

**Actual behavior**
5. There isn't an input to enter the verification code, and the submit button SAVE was replace by the Resend Code option

**Expected behavior**
5. There is an input to enter the verification code, a button to save/verify code, and a link text to resend the verification code.

**Screenshots**
![image](https://user-images.githubusercontent.com/6604846/78323139-4fca3080-7547-11ea-9322-26a0a66b8d36.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
the text that explains the sending of the verification code is incomplete, it should be: "Verifique seu e-mail - enviamos um e-mail com um código de confirmação com 6 dígitos. Insira o código acima para prosseguir com a redefinição da senha."

the save/recover button should open a new screen to type the new password (new password and repeat password)

**Comment by JoseClaudioADS** [comment]
This bug should be reviewed. We use the Firebase platform to recover passwords. The platform works with sending links to change the password and does not send codes for confirmation. I believe that this bug would be valid, if we develop the password recovery platform.

**Comment by maioni** [comment]
Closing this issue, the new way is much better than one designed before.
