### ISSUE TITLE
[UX] Some emojis are NOT displayed on text missions

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#42]
**Describe the bug**
[UX] Some emojis are NOT displayed on text missions

**To Reproduce**
1. Already login and contact already registered
2. Go to a contact details screen
3. Check the mission's text

**Actual behavior**
4. Some emojis are NOT displayed on text missions

**Expected behavior**
4. All emojis are displayed on text missions

**Screenshots**
![image](https://user-images.githubusercontent.com/6604846/78324411-07ad0d00-754b-11ea-920b-3bf778ee4242.png)
![image](https://user-images.githubusercontent.com/6604846/78324421-10054800-754b-11ea-9b54-e90b396ee215.png)
![image](https://user-images.githubusercontent.com/6604846/78324427-13003880-754b-11ea-938b-06e682bcb5d8.png)
![image](https://user-images.githubusercontent.com/6604846/78324434-15fb2900-754b-11ea-8311-1db85bcc1428.png)
![image](https://user-images.githubusercontent.com/6604846/78324440-18f61980-754b-11ea-8a19-8dcf57855e06.png)
![image](https://user-images.githubusercontent.com/6604846/78324446-1b587380-754b-11ea-8c7c-02839a45cc0f.png)
![image](https://user-images.githubusercontent.com/6604846/78324456-214e5480-754b-11ea-9d36-6a2a664b939d.png)
![image](https://user-images.githubusercontent.com/6604846/78324460-24494500-754b-11ea-9caa-f9000d3d9088.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by fhelipesousa** [comment]
If this issue could not be done, the emoji can be remove.

**Comment by JoseClaudioADS** [comment]
I tested it and apparently it's ok. Something must have fixed it.

**Comment by maioni** [comment]
Fixed!
