### ISSUE TITLE
[BUG] NaN Days of without mission

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#47]
**Describe the bug**
[BUG] there is no vertical scrolling on home screen (list of contacts)

**To Reproduce**
1. Already login
2. Add anew contact
3. Check contact details, but don't complet any mission (0 misssion)
4. Go back to the home screen (list of contatcs)
5. Repeat steps from 2 to 4

**Actual behavior**
4. It shows NaN days without mission: "NaN dias sem missão"
5. It shows You dis 0 missions today: "Você fez 0 missões hoje!"

**Expected behavior**
4. It shows You dis 0 missions today: "Você fez 0 missões hoje!"
5. It shows You dis 0 missions today: "Você fez 0 missões hoje!"

**Screenshots**
![image](https://user-images.githubusercontent.com/6604846/78329536-54e3ab80-7558-11ea-959e-017e39d28242.png)
![image](https://user-images.githubusercontent.com/6604846/78329644-ad1aad80-7558-11ea-9fcb-a4d84fce2353.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by GustavoMottaTranche** [comment]
Same issue as #30

**Comment by maioni** [comment]
Fixed!
