### ISSUE TITLE
[UX] Fix text to lower case: Costura and Crochê

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#49]
**Describe the bug**
[UX] Fix text to lower case: Costura and Crochê

**To Reproduce**
1. Already login
2. Add a new contact
3. Go to contact details
4. Check the mission text: "Hora da Arte"

**Actual behavior**
4. "...Costura, Crochê..."

**Expected behavior**
4. "...costura, crochê..." (lower case)

**Screenshots**
![image](https://user-images.githubusercontent.com/6604846/78330263-f4556e00-7559-11ea-98bc-8bb2ce87e29a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by fhelipesousa** [comment]
It will be fixed with properties file (Task #23)

**Comment by JoseClaudioADS** [comment]
I anticipated this fix, but the word "Costura" was capitalized.

**Comment by JoseClaudioADS** [comment]
Remembering. Change applied only to new registered contacts.
